### ISSUE TITLE
Hall_GPEFSMData

### ISSUE THREAD

**Issue by mathew-hall** [researchart/icsme16#8] opened 2016-07-01 16:11 UTC

**Comment by agurfinkel** [comment] 2016-07-27 00:01
The artifact consists of a package to reproduce the experiments and
the analysis in the corresponding paper. Unfortunately, since I did
not read the original paper, it is hard to understand what the actual
data and experiments are.

However, I can confirm that the artifact corresponds to the
scorecard. I was able to install a docker container and look at
Jupyter Notebook.

The artifact supports the empirical evaluation and conclusions in the
paper. The analysis can be re-used by other researchers.

A note to the authors, on OSX, I had to install the artifact in my
home directory. Docker complained otherwise. The rest of the
instructions were easy to follow.

**Comment by davidlo83** [comment] 2016-07-28 10:10
Dear Neil, Matthew, Tim, and Olga,

Together with my co-reviewer, we have read the 2-page description and tried out the artifact. The following is our review:

[Insightful]

> Timely (i.e., addresses a problem that is most current and most pressing)?
> The authors have a paper accepted by the technical track of ICSME 2016 on inferring state transition functions during EFSM inference. This artifact allows others to replicate the findings presented in the paper, and thus it is timely. As a suggestion: it would be great if the authors further stress the timeliness of advancing research in EFSM inference. 
> 
> Makes researchers “smarter” in some way (e.g., identifies and fills some significant gap in prior work)?
> The artifact makes it easy for researchers to advance the field of specification inference by allowing others to replicate and extend the latest work in the area.

[Useful]

> Serves a useful purpose?
> Please refer to the points above.
> 
> Serves a purpose that would otherwise be tedious, prolonged, awkward, or impossible?
> Without the artifact it would be hard for other researchers to replicate the findings of the ICSME 2016 paper. The 2-page description states: "Without the script to download and compile our tool, there is a risk that the reader wishing to replicate our experiments could download the wrong version of the tool (potentially a subsequent version in which our algorithms have been changed), leading to invalid comparisons." I agree with this assessment.
> 
> Cost-effective?
> No information is provided in the 2-page description.

[Usable (co-reviewed by Xuan-Bach L. Dinh)]
- The documents provided are sufficient. One point is that the Makefile causes permission problem when doing "hg clone" by the Makefile. So, I had to go directly to the repo and do a manual clone of the repo myself instead of using the provided Makefile. 
- After manually cloning the repo, the Makefile just runs smoothly and allows me to compile the project. However, the jar file generated are at higher versions than the one that the Makefile expect. Thus, again I need to modify the Makefile a little bit to make sure that the generated jar file versions are matched. After this step, the tool automatically runs and generates the results.

[Recommendation]

maybe accept

Thank you for your attention.

David

**Comment by ghost** [comment] 2016-07-29 03:58
This artifact consists of a package for experiments conducted in an ICSME 2016 paper on inferring state transition functions during EFSM inference.

**Recommendation**
‘? accept’.

**Insightful**

The idea of the paper is interesting, timely, and relevant for this ICSME 2016 artifact track.

The paper is well motivated and its problem as well as its obtained findings are detailed in the paper entitled “_Inferring Computational State Machine Models from Program Executions_” accepted in publication in ICSME 2016.

**Useful**

This artifact can be very useful for the research community working on data transformations.

It can greatly help for replication and comparison purposes in this area.

**Usable**

The authors adhere to the ICSME artifact track guidelines and particularly the three required dimensions: insightfulness, usefulness, and usability.

Details related to the artifact package are provided including those related to hardware requirements, download, and running of the experiments.

The artifact package (along with its details) are available online.

Overall, I think this artifact can be useful for researchers working on data transformations in particular those willing to replicate the authors’ work and--or use this artifact for comparison purposes.

**Comment by timm** [comment] 2016-08-01 22:00
marked as accept

**Closed as completed** 2016-10-07 14:15 UTC
Labels: Accept, thrice
